name: CI

on:
  push:
    branches:
      - main
  pull_request: {}


jobs:
  rustfmt:
    name: "Rust Format"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt

    - name: fmt
      run: cargo fmt --all --check

  clippy:
    name: "Clippy"
    runs-on: ubuntu-latest

    env:
        SQLX_OFFLINE: 1
        DATABASE_URL: postgres://itil_back:itil_back@localhost:5432/itil_back
        APP_DATABASE__URL: postgres://itil_back:itil_back@localhost:5432/itil_back
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: itil_back
          POSTGRES_USER: itil_back
          POSTGRES_PASSWORD: itil_back
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy
    - name: migrate
      run: cargo db reset
    - name: clippy
      run: cargo clippy --all-targets -- -D warnings

  test:
    name: "Test"
    runs-on: ubuntu-latest

    env:
        DATABASE_URL: postgres://itil_back_test:itil_back_test@localhost:5432/itil_back_test
        APP_DATABASE__URL: postgres://itil_back_test:itil_back_test@localhost:5432/itil_back_test
    services:
      postgres_test:
        image: postgres
        env:
          POSTGRES_DB: itil_back_test
          POSTGRES_USER: itil_back_test
          POSTGRES_PASSWORD: itil_back_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
    - uses: actions/checkout@v3
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - name: migrate
      run: cargo db reset
    - name: test
      run: cargo test
